services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - SIGNUPS_ALLOWED=false
      - TZ=America/Santiago
      # NOTA IMPORTANTE: En docker-compose.yml, cada signo '$' del hash Argon2 debe duplicarse como '$$'
      - ADMIN_TOKEN=$$argon2id$$v=19$$m=65540,t=3,p=4$$<TU_HASH_ARGON2_AQUI>$$<TU_SALT_ARGON2_AQUI>
    volumes:
      - ./data:/data
    ports:
      - 8445:80
